CREATE TABLE IF NOT EXISTS pedido (
  id_pedido BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  codigo_pedido VARCHAR(40) NOT NULL UNIQUE,
  id_cliente BIGINT UNSIGNED NOT NULL,
  canal_origen ENUM('WEB','CHATBOT_WEB') NOT NULL,
  modalidad ENUM('RECOJO','DELIVERY') NOT NULL,
  estado_actual ENUM('CREADO','PAGO_PENDIENTE','PAGO_RECHAZADO','PAGO_APROBADO','CONFIRMADO','EN_PREPARACION','LISTO_RECOJO','LISTO_DESPACHO','EN_CAMINO','ENTREGADO','CANCELADO','ANULADO') NOT NULL,
  tipo_comprobante ENUM('BOLETA','FACTURA') NOT NULL,
  id_direccion_entrega BIGINT UNSIGNED NULL,
  subtotal DECIMAL(12,2) NOT NULL,
  descuento_total DECIMAL(12,2) NOT NULL DEFAULT 0,
  impuesto_total DECIMAL(12,2) NOT NULL DEFAULT 0,
  total DECIMAL(12,2) NOT NULL,
  usuario_creacion BIGINT UNSIGNED NULL,
  usuario_actualizacion BIGINT UNSIGNED NULL,
  fecha_creacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  fecha_actualizacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_pedido_cliente FOREIGN KEY (id_cliente) REFERENCES cliente_perfil(id_cliente),
  CONSTRAINT fk_pedido_direccion FOREIGN KEY (id_direccion_entrega) REFERENCES cliente_direccion(id_direccion),
  CONSTRAINT fk_pedido_usuario_creacion FOREIGN KEY (usuario_creacion) REFERENCES usuario(id_usuario),
  CONSTRAINT fk_pedido_usuario_actualizacion FOREIGN KEY (usuario_actualizacion) REFERENCES usuario(id_usuario)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS pedido_estado_transicion_permitida (
  id_transicion BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  estado_origen ENUM('CREADO','PAGO_PENDIENTE','PAGO_RECHAZADO','PAGO_APROBADO','CONFIRMADO','EN_PREPARACION','LISTO_RECOJO','LISTO_DESPACHO','EN_CAMINO','ENTREGADO','CANCELADO','ANULADO') NOT NULL,
  estado_destino ENUM('CREADO','PAGO_PENDIENTE','PAGO_RECHAZADO','PAGO_APROBADO','CONFIRMADO','EN_PREPARACION','LISTO_RECOJO','LISTO_DESPACHO','EN_CAMINO','ENTREGADO','CANCELADO','ANULADO') NOT NULL,
  actor_tipo ENUM('CLIENTE','COCINA','ADMIN','SISTEMA') NOT NULL,
  activo TINYINT(1) NOT NULL DEFAULT 1,
  UNIQUE KEY uq_pedido_transicion (estado_origen, estado_destino, actor_tipo)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS pedido_estado_historial (
  id_historial BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  id_pedido BIGINT UNSIGNED NOT NULL,
  estado_origen ENUM('CREADO','PAGO_PENDIENTE','PAGO_RECHAZADO','PAGO_APROBADO','CONFIRMADO','EN_PREPARACION','LISTO_RECOJO','LISTO_DESPACHO','EN_CAMINO','ENTREGADO','CANCELADO','ANULADO') NULL,
  estado_destino ENUM('CREADO','PAGO_PENDIENTE','PAGO_RECHAZADO','PAGO_APROBADO','CONFIRMADO','EN_PREPARACION','LISTO_RECOJO','LISTO_DESPACHO','EN_CAMINO','ENTREGADO','CANCELADO','ANULADO') NOT NULL,
  actor_id BIGINT UNSIGNED NULL,
  actor_tipo ENUM('CLIENTE','COCINA','ADMIN','SISTEMA') NOT NULL,
  motivo VARCHAR(255) NULL,
  fecha_creacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_pedido_historial_pedido FOREIGN KEY (id_pedido) REFERENCES pedido(id_pedido) ON DELETE CASCADE,
  CONSTRAINT fk_pedido_historial_actor FOREIGN KEY (actor_id) REFERENCES usuario(id_usuario)
) ENGINE=InnoDB;

CREATE INDEX idx_pedido_estado_fecha ON pedido(estado_actual, fecha_creacion);
CREATE INDEX idx_pedido_cliente_fecha ON pedido(id_cliente, fecha_creacion);

INSERT INTO pedido_estado_transicion_permitida (estado_origen, estado_destino, actor_tipo, activo)
VALUES
('CREADO','PAGO_PENDIENTE','CLIENTE',1),
('PAGO_PENDIENTE','PAGO_APROBADO','SISTEMA',1),
('PAGO_PENDIENTE','PAGO_RECHAZADO','SISTEMA',1),
('PAGO_APROBADO','CONFIRMADO','ADMIN',1),
('CONFIRMADO','EN_PREPARACION','COCINA',1),
('EN_PREPARACION','LISTO_RECOJO','COCINA',1),
('EN_PREPARACION','LISTO_DESPACHO','COCINA',1),
('LISTO_DESPACHO','EN_CAMINO','ADMIN',1),
('LISTO_RECOJO','ENTREGADO','COCINA',1),
('EN_CAMINO','ENTREGADO','ADMIN',1),
('CREADO','CANCELADO','CLIENTE',1),
('PAGO_PENDIENTE','CANCELADO','CLIENTE',1),
('CREADO','ANULADO','ADMIN',1),
('PAGO_RECHAZADO','ANULADO','ADMIN',1)
ON DUPLICATE KEY UPDATE activo = VALUES(activo);
